FROM php:7.4-cli-alpine
LABEL maintainer="Adriano Carrijo <@adrianovc>"

# 01. Install some dependencies
RUN apk add --update \
    git \
    wget \
    py-pip \
    ffmpeg \
    && rm -rf /var/cache/apk/*

# 02. Copy php.ini file
RUN cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# 04. Clean cache
RUN rm -rf /var/lib/apt/lists/*

# 05. Install Deezer Spleeter
RUN pip install spleeter

# 06. Copy project files to build
COPY . /var/www/html/

# 07. Run composer
RUN wget -cO - https://getcomposer.org/composer-stable.phar > /usr/local/bin/composer && \
    chmod +x /usr/local/bin/composer && \
    composer install \
    --no-dev \
    --prefer-dist \
    --no-scripts \
    --ignore-platform-reqs \
    --no-progress \
    --optimize-autoloader \
    --no-interaction
